### ISSUE TITLE
problem install kamrat

### ISSUE THREAD

**Issue by MorillonLab** [Transipedia/KaMRaT#1]
Dear Haoliang

i have some trouble installing the last version of kamrat

it won't compile kamratRank, because of a command in scorer.cpp

here is the error

g++ -c kamratRank.cpp data_struct/scorer.cpp data_struct/feature_elem.cpp utils/vect_opera.cpp -fopenmp -lmlpack -larmadillo  -Wall -Werror -g -std=c++14
data_struct/scorer.cpp: In function ‘const double CalcTtestScore(const arma::Mat<double>&&, const arma::Mat<double>&&, bool)’:
data_struct/scorer.cpp:121:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2)),
                                                               ^
data_struct/scorer.cpp:121:117: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2)),
                                                                                                                     ^
data_struct/scorer.cpp: In function ‘const double CalcSNRScore(const arma::Mat<double>&&, const arma::Mat<double>&&)’:
data_struct/scorer.cpp:150:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2));
                                                               ^
data_struct/scorer.cpp:150:117: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2));
                                                                                                                     ^
data_struct/scorer.cpp: In function ‘const double CalcSDScore(const arma::Mat<double>&)’:
data_struct/scorer.cpp:237:58: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘const double’ in return
     return arma::mean(arma::stddev(arma_count_vect, 0, 1)); // arma_count_vect is not processed by .elem(), so still row vectors
                                                          ^
data_struct/scorer.cpp: In function ‘const double CalcRSDScore(const arma::Mat<double>&)’:
data_struct/scorer.cpp:242:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
     double sd = arma::mean(arma::stddev(arma_count_vect, 0, 1)),
                                                               ^
Makefile:15: recipe for target 'kamratRank' failed
 

Thanks for your help

Ugo

**Comment by yoann-dufresne** [comment]
Hello @MorillonLab,

We are refactoring the code to publish a v1.2 of KaMRaT.
Could you try the dev branch ? It works on my side.
To compile from the root of the project : ```cmake . && make -j```
Then the kamrat binary is in apps directory.

If this works, you can use this version. If not, we will see how to solve the compilation error that you raised.

Yoann

**Comment by MorillonLab** [comment]
Hi Yoann 
thanks for your answer
i tried with the dev branch, but there is still the same error.

here is the cmake : 
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0")  
-- Found Armadillo: /usr/include (found version "8.400.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev

and the make : 

[  6%] Building CXX object src/utils/CMakeFiles/vectOp.dir/vect_opera.cpp.o
[  6%] Building CXX object src/utils/CMakeFiles/indexLoading.dir/index_loading.cpp.o
[ 13%] Building CXX object src/data_struct/CMakeFiles/dataStruct.dir/contig_elem.cpp.o
[ 13%] Building CXX object src/utils/CMakeFiles/seqCoding.dir/seq_coding.cpp.o
[ 17%] Building CXX object src/data_struct/CMakeFiles/dataStruct.dir/scorer.cpp.o
[ 24%] Building CXX object src/data_struct/CMakeFiles/dataStruct.dir/merge_knot.cpp.o
[ 24%] Building CXX object src/data_struct/CMakeFiles/dataStruct.dir/feature_elem.cpp.o
[ 27%] Linking CXX static library libseqCoding.a
[ 27%] Built target seqCoding
[ 31%] Linking CXX static library libvectOp.a
[ 31%] Built target vectOp
[ 34%] Linking CXX static library libindexLoading.a
[ 34%] Built target indexLoading
[ 41%] Building CXX object src/cmds/CMakeFiles/kamratIndex.dir/kamratIndex.cpp.o
[ 41%] Building CXX object src/cmds/CMakeFiles/kamratMask.dir/kamratMask.cpp.o
[ 44%] Building CXX object src/cmds/CMakeFiles/kamratFilter.dir/kamratFilter.cpp.o
[ 48%] Building CXX object src/cmds/CMakeFiles/kamratQuery.dir/kamratQuery.cpp.o
[ 51%] Linking CXX static library libkamratMask.a
[ 51%] Built target kamratMask
[ 55%] Linking CXX static library libkamratQuery.a
[ 55%] Built target kamratQuery
[ 58%] Linking CXX static library libkamratFilter.a
[ 58%] Built target kamratFilter
[ 62%] Linking CXX static library libkamratIndex.a
[ 62%] Built target kamratIndex
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcTtestScore_old(const arma::Mat<double>&&, const arma::Mat<double>&&, bool)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:179:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2)),
                                                               ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:179:117: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2)),
                                                                                                                     ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcSNRScore_old(const arma::Mat<double>&&, const arma::Mat<double>&&)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:224:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2));
                                                               ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:224:117: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
            stddev1 = arma::mean(arma::stddev(arma_count_vect1)), stddev2 = arma::mean(arma::stddev(arma_count_vect2));
                                                                                                                     ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcSDScore_old(const arma::Mat<double>&)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:353:58: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘const double’ in return
     return arma::mean(arma::stddev(arma_count_vect, 0, 1)); // arma_count_vect is not processed by .elem(), so still row vectors
                                                          ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcRSD1Score_old(const arma::Mat<double>&)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:368:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
     double sd = arma::mean(arma::stddev(arma_count_vect, 0, 1)),
                                                               ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcRSD2Score_old(const arma::Mat<double>&)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:385:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
     double sd = arma::mean(arma::stddev(arma_count_vect, 0, 1)),
                                                               ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp: In function ‘const double CalcRSD3Score_old(const arma::Mat<double>&)’:
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:416:63: error: cannot convert ‘const arma::Op<arma::mtOp<double, arma::Mat<double>, arma::op_stddev>, arma::op_mean>’ to ‘double’ in initialization
     double sd = arma::mean(arma::stddev(arma_count_vect, 0, 1)),
                                                               ^
/home/ugo/TOOLS/kamrat_13_6_22/KaMRaT-dev/src/data_struct/scorer.cpp:417:61: error: cannot convert ‘const arma::Op<arma::Op<arma::Mat<double>, arma::op_median>, arma::op_mean>’ to ‘double’ in initialization
            mdn = arma::mean(arma::median(arma_count_vect, 1));
                                                             ^
src/data_struct/CMakeFiles/dataStruct.dir/build.make:117: recipe for target 'src/data_struct/CMakeFiles/dataStruct.dir/scorer.cpp.o' failed
make[2]: *** [src/data_struct/CMakeFiles/dataStruct.dir/scorer.cpp.o] Error 1
CMakeFiles/Makefile2:439: recipe for target 'src/data_struct/CMakeFiles/dataStruct.dir/all' failed
make[1]: *** [src/data_struct/CMakeFiles/dataStruct.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Ugo

**Comment by hl-xue** [comment]
Dear Ugo,

Based on your error message, I think there are some issues related to armadillo library version (installed via `mlpack`).  If you were installing `mlpack` by yourself, could you please check if its version is 3.3.2?
Alternatively, I would suggest to use the singularity version instead.  This should avoid all issues of this kind.

Please let us know if you encounter any further difficulty.
Best wishes,
Haoliang
